---
- name: "PLAY1 | Deploiement des serveurs web"
  hosts: webservers

  vars:
    pkg_apache: apache2

  tasks:
    # Appel du module apt pour vérifier/installer le package apache2
    - name: "Installation package apache2"
      ansible.builtin.apt:
        name: "{{ pkg_apache }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

- name: "PLAY2 | Deploiement HAPROXY"
  hosts: haproxy

  vars:
    pkg_haproxy: haproxy

  tasks:
    # Appel du module yum pour vérifier/installer le package haproxy
    - name: "Installation haproxy"
      ansible.builtin.yum:
        name: "{{ pkg_haproxy }}"
        state: present
    
    # Appel du module template : fichiers dynamique qui se construit au travers de variables
    - name: "Configuration du haproxy"
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0640'
