---
- name: "PLAY1 | Deploiement des serveurs web"
  hosts: webservers
  gather_facts: True

  vars:
    pkg_apache: apache2
    #ma_variable2: "declarée dans le playbook"

  tasks:
    # Appel du module apt pour vérifier/installer le package apache2
    - name: "Installation package apache2"
      ansible.builtin.apt:
        name: "{{ pkg_apache }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: "Deploiement du site"
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

- name: "PLAY2 | Deploiement HAPROXY"
  hosts: haproxy
  gather_facts: yes
  become: true

  roles:
    - ansible_role_haproxy