---
- name: "PLAY demo facts"
  hosts: linux
  gather_subset:
    - '!all'
    - 'network'
  
  tasks:
    - name: "Enregister un facts"
      ansible.builtin.set_fact:
        ansible_fact_perso: something
        cacheable: yes